"""
core/dojo/problems.py — "LeetCode for Data Science" problem bank.

A large, deterministic catalogue spanning NumPy, statistics, linear algebra,
probability/information theory, ML metrics, ML-from-scratch, data manipulation,
feature engineering, distances, NLP basics, time series, and classic algorithms.

Each problem is built with mk(), which auto-derives the starter stub from the
reference signature. All reference solutions are verified by tests/test_dojo.py
(each must pass its own precomputed expected outputs; a wrong stub must fail).

Schema (per problem): id, category, title, difficulty(1-5), fn_name, concept,
math, intuition, starter_code, reference_solution, test_inputs, tolerance,
hints[], common_mistakes[], topics[], constraints, related_hyperparameter,
related_arch.
"""

from typing import Any, Dict, List


def _starter_from_ref(ref: str) -> str:
    sig = ref.strip().split("\n", 1)[0]
    return sig + "\n    # Your code here\n    pass\n"


def mk(id, cat, title, diff, fn, concept, math, ref, tests, *,
       tol=1e-6, topics=None, hints=None, mistakes=None, intuition=None,
       starter=None, constraints="", related_hp=None, related_arch=None) -> Dict[str, Any]:
    return {
        "id": id,
        "category": cat,
        "title": title,
        "difficulty": diff,
        "fn_name": fn,
        "concept": concept,
        "math": math or "—",
        "intuition": intuition or concept,
        "starter_code": starter or _starter_from_ref(ref),
        "reference_solution": ref,
        "test_inputs": tests,
        "tolerance": tol,
        "hints": hints or ["Break the problem into small vectorized NumPy steps."],
        "common_mistakes": mistakes or ["Mind input types (numeric lists arrive as NumPy arrays) and the output shape."],
        "topics": topics or [cat],
        "constraints": constraints,
        "related_hyperparameter": related_hp,
        "related_arch": related_arch,
    }


DS_PROBLEMS: List[Dict[str, Any]] = [

    # ============================ NUMPY BASICS ============================
    mk("np_array_sum", "NumPy", "Array Sum", 1, "array_sum",
       "Sum all elements of an array.", "sum(x_i)",
       "def array_sum(x):\n    return np.sum(x)\n",
       [{"x": [1, 2, 3, 4]}, {"x": [[1, 2], [3, 4]]}],
       topics=["NumPy", "Aggregation"]),
    mk("np_mean", "NumPy", "Array Mean", 1, "array_mean",
       "Average of all elements.", "mean = sum(x)/n",
       "def array_mean(x):\n    return np.mean(x)\n",
       [{"x": [2, 4, 6]}, {"x": [1, 2, 3, 4, 5]}], topics=["NumPy", "Statistics"]),
    mk("np_elementwise_mul", "NumPy", "Element-wise Multiply", 1, "elementwise_multiply",
       "Multiply two arrays element-wise.", "z_i = a_i * b_i",
       "def elementwise_multiply(a, b):\n    return a * b\n",
       [{"a": [1, 2, 3], "b": [4, 5, 6]}], topics=["NumPy"]),
    mk("np_dot", "NumPy", "Dot Product", 1, "dot_product",
       "Dot product of two vectors.", "a·b = sum(a_i b_i)",
       "def dot_product(a, b):\n    return np.dot(a, b)\n",
       [{"a": [1, 2, 3], "b": [4, 5, 6]}], topics=["NumPy", "Linear Algebra"]),
    mk("np_matmul", "NumPy", "Matrix Multiply", 2, "matrix_multiply",
       "Multiply two matrices.", "C = A @ B",
       "def matrix_multiply(A, B):\n    return A @ B\n",
       [{"A": [[1, 2], [3, 4]], "B": [[5, 6], [7, 8]]}], topics=["NumPy", "Linear Algebra"],
       mistakes=["Use @ (matmul), not * (element-wise)."]),
    mk("np_transpose", "NumPy", "Transpose", 1, "transpose",
       "Transpose a matrix.", "A^T",
       "def transpose(A):\n    return A.T\n",
       [{"A": [[1, 2, 3], [4, 5, 6]]}], topics=["NumPy", "Linear Algebra"]),
    mk("np_flatten", "NumPy", "Flatten", 1, "flatten",
       "Flatten a matrix into a 1-D array (row-major).", "reshape(-1)",
       "def flatten(A):\n    return A.reshape(-1)\n",
       [{"A": [[1, 2], [3, 4]]}], topics=["NumPy"]),
    mk("np_minmax", "NumPy", "Min-Max Normalize", 2, "min_max_normalize",
       "Scale values to [0, 1].", "(x - min) / (max - min)",
       "def min_max_normalize(x):\n    lo, hi = np.min(x), np.max(x)\n    return (x - lo) / (hi - lo)\n",
       [{"x": [2, 4, 6, 8]}, {"x": [10, 20, 30]}], topics=["NumPy", "Feature Engineering"],
       mistakes=["Divide by (max - min), not max."]),
    mk("np_standardize", "NumPy", "Standardize (Z-score)", 2, "standardize",
       "Zero mean, unit variance.", "(x - mean) / std",
       "def standardize(x):\n    return (x - np.mean(x)) / np.std(x)\n",
       [{"x": [1, 2, 3, 4, 5]}], topics=["NumPy", "Statistics", "Feature Engineering"]),
    mk("np_clip", "NumPy", "Clip Values", 1, "clip_values",
       "Clamp values into [lo, hi].", "clip(x, lo, hi)",
       "def clip_values(x, lo, hi):\n    return np.clip(x, lo, hi)\n",
       [{"x": [-2, 0, 5, 11], "lo": 0, "hi": 10}], topics=["NumPy"]),
    mk("np_cumsum", "NumPy", "Cumulative Sum", 1, "cumulative_sum",
       "Running total along the array.", "y_i = sum(x_0..x_i)",
       "def cumulative_sum(x):\n    return np.cumsum(x)\n",
       [{"x": [1, 2, 3, 4]}], topics=["NumPy"]),
    mk("np_rowsums", "NumPy", "Row Sums", 2, "row_sums",
       "Sum each row of a matrix.", "sum over axis=1",
       "def row_sums(A):\n    return np.sum(A, axis=1)\n",
       [{"A": [[1, 2, 3], [4, 5, 6]]}], topics=["NumPy"],
       mistakes=["axis=1 sums across columns within each row."]),
    mk("np_colmeans", "NumPy", "Column Means", 2, "col_means",
       "Mean of each column.", "mean over axis=0",
       "def col_means(A):\n    return np.mean(A, axis=0)\n",
       [{"A": [[1, 2], [3, 4], [5, 6]]}], topics=["NumPy"]),
    mk("np_argmax", "NumPy", "Argmax Index", 1, "argmax_index",
       "Index of the maximum element.", "argmax(x)",
       "def argmax_index(x):\n    return int(np.argmax(x))\n",
       [{"x": [3, 1, 4, 1, 5, 9, 2]}], topics=["NumPy"]),
    mk("np_count_positive", "NumPy", "Count Positives", 1, "count_positive",
       "How many elements are > 0.", "sum(x > 0)",
       "def count_positive(x):\n    return int(np.sum(x > 0))\n",
       [{"x": [-1, 2, -3, 4, 0, 5]}], topics=["NumPy"]),
    mk("np_relu_zero", "NumPy", "Replace Negatives with Zero", 1, "replace_negatives_zero",
       "Set negative entries to 0.", "max(0, x)",
       "def replace_negatives_zero(x):\n    return np.where(x < 0, 0, x)\n",
       [{"x": [-2, 3, -1, 4]}], topics=["NumPy"]),
    mk("np_l2norm", "NumPy", "L2 Norm", 1, "l2_norm",
       "Euclidean length of a vector.", "sqrt(sum(x^2))",
       "def l2_norm(x):\n    return np.sqrt(np.sum(x ** 2))\n",
       [{"x": [3, 4]}, {"x": [1, 2, 2]}], topics=["NumPy", "Linear Algebra"]),
    mk("np_broadcast_add", "NumPy", "Broadcast Add Vector", 2, "broadcast_add_vector",
       "Add a row vector to every row of a matrix.", "A + v (broadcast)",
       "def broadcast_add_vector(A, v):\n    return A + v\n",
       [{"A": [[1, 2, 3], [4, 5, 6]], "v": [10, 20, 30]}], topics=["NumPy", "Broadcasting"]),

    # ============================ STATISTICS ============================
    mk("st_variance", "Statistics", "Variance", 2, "variance",
       "Population variance.", "var = mean((x - mean)^2)",
       "def variance(x):\n    return np.mean((x - np.mean(x)) ** 2)\n",
       [{"x": [1, 2, 3, 4, 5]}], topics=["Statistics"]),
    mk("st_std", "Statistics", "Standard Deviation", 2, "std_dev",
       "Population standard deviation.", "sqrt(var)",
       "def std_dev(x):\n    return np.std(x)\n",
       [{"x": [2, 4, 4, 4, 5, 5, 7, 9]}], topics=["Statistics"]),
    mk("st_median", "Statistics", "Median", 2, "median",
       "Middle value of sorted data.", "median(x)",
       "def median(x):\n    return float(np.median(x))\n",
       [{"x": [3, 1, 2]}, {"x": [4, 1, 3, 2]}], topics=["Statistics"]),
    mk("st_percentile", "Statistics", "Percentile", 3, "percentile",
       "The p-th percentile of the data.", "percentile(x, p)",
       "def percentile(x, p):\n    return float(np.percentile(x, p))\n",
       [{"x": [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], "p": 25}], topics=["Statistics"]),
    mk("st_covariance", "Statistics", "Covariance", 3, "covariance",
       "Covariance between two equal-length series.", "mean((x-mx)(y-my))",
       "def covariance(x, y):\n    return float(np.mean((x - np.mean(x)) * (y - np.mean(y))))\n",
       [{"x": [1, 2, 3, 4], "y": [2, 4, 6, 8]}], topics=["Statistics"]),
    mk("st_pearson", "Statistics", "Pearson Correlation", 3, "pearson_correlation",
       "Linear correlation coefficient in [-1, 1].", "cov(x,y)/(std_x std_y)",
       "def pearson_correlation(x, y):\n    xm, ym = x - np.mean(x), y - np.mean(y)\n    return float(np.sum(xm * ym) / (np.sqrt(np.sum(xm**2)) * np.sqrt(np.sum(ym**2))))\n",
       [{"x": [1, 2, 3, 4, 5], "y": [2, 4, 5, 4, 5]}], topics=["Statistics"],
       mistakes=["Normalize by the product of the two norms, not the variance."]),
    mk("st_weighted_mean", "Statistics", "Weighted Mean", 2, "weighted_mean",
       "Mean weighted by importance.", "sum(w x)/sum(w)",
       "def weighted_mean(x, w):\n    return float(np.sum(x * w) / np.sum(w))\n",
       [{"x": [1, 2, 3], "w": [1, 2, 3]}], topics=["Statistics"]),
    mk("st_iqr", "Statistics", "Interquartile Range", 3, "iqr",
       "IQR = Q3 - Q1.", "percentile75 - percentile25",
       "def iqr(x):\n    return float(np.percentile(x, 75) - np.percentile(x, 25))\n",
       [{"x": [1, 2, 3, 4, 5, 6, 7, 8]}], topics=["Statistics"]),
    mk("st_range", "Statistics", "Range (Spread)", 1, "data_range",
       "Max minus min.", "max - min",
       "def data_range(x):\n    return float(np.max(x) - np.min(x))\n",
       [{"x": [4, 9, 2, 7]}], topics=["Statistics"]),
    mk("st_mode", "Statistics", "Mode (Most Frequent)", 2, "mode_value",
       "Most frequent label in a list of strings.", "argmax of counts",
       "def mode_value(items):\n    counts = {}\n    for it in items:\n        counts[it] = counts.get(it, 0) + 1\n    best, bestc = items[0], -1\n    for k in counts:\n        if counts[k] > bestc:\n            best, bestc = k, counts[k]\n    return best\n",
       [{"items": ["a", "b", "a", "c", "a", "b"]}], topics=["Statistics", "Data Manipulation"]),

    # ============================ LINEAR ALGEBRA ============================
    mk("la_cosine", "Linear Algebra", "Cosine Similarity", 2, "cosine_similarity",
       "Cosine of the angle between two vectors.", "(a·b)/(|a||b|)",
       "def cosine_similarity(a, b):\n    return float(np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b)))\n",
       [{"a": [1, 0, 1], "b": [1, 1, 0]}], topics=["Linear Algebra", "Distances"]),
    mk("la_euclidean", "Linear Algebra", "Euclidean Distance", 1, "euclidean_distance",
       "Straight-line distance between points.", "sqrt(sum((a-b)^2))",
       "def euclidean_distance(a, b):\n    return float(np.sqrt(np.sum((a - b) ** 2)))\n",
       [{"a": [0, 0], "b": [3, 4]}], topics=["Linear Algebra", "Distances"]),
    mk("la_manhattan", "Linear Algebra", "Manhattan Distance", 1, "manhattan_distance",
       "Sum of absolute coordinate differences.", "sum(|a-b|)",
       "def manhattan_distance(a, b):\n    return float(np.sum(np.abs(a - b)))\n",
       [{"a": [1, 2, 3], "b": [4, 0, 3]}], topics=["Linear Algebra", "Distances"]),
    mk("la_trace", "Linear Algebra", "Matrix Trace", 1, "matrix_trace",
       "Sum of the diagonal.", "sum(A_ii)",
       "def matrix_trace(A):\n    return float(np.trace(A))\n",
       [{"A": [[1, 2], [3, 4]]}], topics=["Linear Algebra"]),
    mk("la_identity", "Linear Algebra", "Identity Matrix", 1, "identity_matrix",
       "Build an n×n identity matrix.", "I_n",
       "def identity_matrix(n):\n    return np.eye(int(n))\n",
       [{"n": 3}], topics=["Linear Algebra"]),
    mk("la_matvec", "Linear Algebra", "Matrix-Vector Product", 2, "matrix_vector_product",
       "Multiply a matrix by a vector.", "A v",
       "def matrix_vector_product(A, v):\n    return A @ v\n",
       [{"A": [[1, 2], [3, 4]], "v": [1, 1]}], topics=["Linear Algebra"]),
    mk("la_symmetric", "Linear Algebra", "Is Symmetric?", 2, "is_symmetric",
       "Return True if A == A^T.", "A == A^T",
       "def is_symmetric(A):\n    return bool(np.allclose(A, A.T))\n",
       [{"A": [[1, 2], [2, 1]]}, {"A": [[1, 2], [3, 1]]}], topics=["Linear Algebra"]),
    mk("la_frobenius", "Linear Algebra", "Frobenius Norm", 2, "frobenius_norm",
       "Matrix norm = sqrt(sum of squares).", "sqrt(sum(A^2))",
       "def frobenius_norm(A):\n    return float(np.sqrt(np.sum(A ** 2)))\n",
       [{"A": [[1, 2], [3, 4]]}], topics=["Linear Algebra"]),
    mk("la_solve", "Linear Algebra", "Solve Linear System", 4, "solve_system",
       "Solve A x = b for x.", "x = A^{-1} b",
       "def solve_system(A, b):\n    return np.linalg.solve(A, b)\n",
       [{"A": [[3, 1], [1, 2]], "b": [9, 8]}], topics=["Linear Algebra"],
       mistakes=["Use np.linalg.solve — never explicitly invert A."]),

    # ============================ PROBABILITY / INFO ============================
    mk("pr_entropy", "Probability", "Shannon Entropy", 3, "entropy",
       "Entropy of a probability distribution (nats).", "-sum(p log p)",
       "def entropy(p):\n    p = p[p > 0]\n    return float(-np.sum(p * np.log(p)))\n",
       [{"p": [0.5, 0.5]}, {"p": [1.0, 0.0]}], topics=["Probability", "Information Theory"],
       mistakes=["Skip zero probabilities — log(0) is undefined."]),
    mk("pr_kl", "Probability", "KL Divergence", 4, "kl_divergence",
       "Divergence of p from q.", "sum(p log(p/q))",
       "def kl_divergence(p, q):\n    mask = p > 0\n    return float(np.sum(p[mask] * np.log(p[mask] / q[mask])))\n",
       [{"p": [0.5, 0.5], "q": [0.25, 0.75]}], topics=["Probability", "Information Theory"]),
    mk("pr_gaussian", "Probability", "Gaussian PDF", 3, "gaussian_pdf",
       "Normal density at x.", "1/(σ√2π) exp(-(x-μ)^2/2σ^2)",
       "def gaussian_pdf(x, mu, sigma):\n    return float(1.0 / (sigma * np.sqrt(2 * np.pi)) * np.exp(-((x - mu) ** 2) / (2 * sigma ** 2)))\n",
       [{"x": 0.0, "mu": 0.0, "sigma": 1.0}], topics=["Probability"]),
    mk("pr_lognorm", "Probability", "Normalize to Distribution", 1, "normalize_distribution",
       "Scale a non-negative vector to sum to 1.", "x / sum(x)",
       "def normalize_distribution(x):\n    return x / np.sum(x)\n",
       [{"x": [1, 1, 2]}], topics=["Probability"]),
    mk("pr_logloss", "Probability", "Binary Log Loss", 3, "log_loss",
       "Binary cross-entropy from probabilities.", "-mean(y log p + (1-y) log(1-p))",
       "def log_loss(p, y):\n    eps = 1e-12\n    p = np.clip(p, eps, 1 - eps)\n    return float(-np.mean(y * np.log(p) + (1 - y) * np.log(1 - p)))\n",
       [{"p": [0.9, 0.1, 0.8], "y": [1, 0, 1]}], topics=["Probability", "ML Metrics"]),

    # ============================ ML METRICS ============================
    mk("m_precision", "ML Metrics", "Precision", 2, "precision",
       "TP / (TP + FP) for binary 0/1 arrays.", "TP/(TP+FP)",
       "def precision(y_pred, y_true):\n    tp = np.sum((y_pred == 1) & (y_true == 1))\n    fp = np.sum((y_pred == 1) & (y_true == 0))\n    return float(tp / (tp + fp)) if (tp + fp) > 0 else 0.0\n",
       [{"y_pred": [1, 1, 0, 1], "y_true": [1, 0, 0, 1]}], topics=["ML Metrics"]),
    mk("m_recall", "ML Metrics", "Recall", 2, "recall",
       "TP / (TP + FN).", "TP/(TP+FN)",
       "def recall(y_pred, y_true):\n    tp = np.sum((y_pred == 1) & (y_true == 1))\n    fn = np.sum((y_pred == 0) & (y_true == 1))\n    return float(tp / (tp + fn)) if (tp + fn) > 0 else 0.0\n",
       [{"y_pred": [1, 0, 0, 1], "y_true": [1, 1, 0, 1]}], topics=["ML Metrics"]),
    mk("m_f1", "ML Metrics", "F1 Score", 3, "f1_score",
       "Harmonic mean of precision and recall.", "2PR/(P+R)",
       "def f1_score(y_pred, y_true):\n    tp = np.sum((y_pred == 1) & (y_true == 1))\n    fp = np.sum((y_pred == 1) & (y_true == 0))\n    fn = np.sum((y_pred == 0) & (y_true == 1))\n    p = tp / (tp + fp) if (tp + fp) > 0 else 0.0\n    r = tp / (tp + fn) if (tp + fn) > 0 else 0.0\n    return float(2 * p * r / (p + r)) if (p + r) > 0 else 0.0\n",
       [{"y_pred": [1, 1, 0, 1, 0], "y_true": [1, 0, 0, 1, 1]}], topics=["ML Metrics"]),
    mk("m_confusion", "ML Metrics", "Confusion Matrix (2×2)", 3, "confusion_matrix",
       "Return [[TN, FP], [FN, TP]].", "counts by (true,pred)",
       "def confusion_matrix(y_pred, y_true):\n    tn = int(np.sum((y_pred == 0) & (y_true == 0)))\n    fp = int(np.sum((y_pred == 1) & (y_true == 0)))\n    fn = int(np.sum((y_pred == 0) & (y_true == 1)))\n    tp = int(np.sum((y_pred == 1) & (y_true == 1)))\n    return [[tn, fp], [fn, tp]]\n",
       [{"y_pred": [1, 0, 1, 0], "y_true": [1, 0, 0, 1]}], topics=["ML Metrics"]),
    mk("m_rmse", "ML Metrics", "RMSE", 2, "rmse",
       "Root mean squared error.", "sqrt(mean((yp-yt)^2))",
       "def rmse(y_pred, y_true):\n    return float(np.sqrt(np.mean((y_pred - y_true) ** 2)))\n",
       [{"y_pred": [2, 0, 2], "y_true": [1, 0, 4]}], topics=["ML Metrics"]),
    mk("m_r2", "ML Metrics", "R² Score", 3, "r2_score",
       "Coefficient of determination.", "1 - SS_res/SS_tot",
       "def r2_score(y_pred, y_true):\n    ss_res = np.sum((y_true - y_pred) ** 2)\n    ss_tot = np.sum((y_true - np.mean(y_true)) ** 2)\n    return float(1 - ss_res / ss_tot)\n",
       [{"y_pred": [2.5, 0.0, 2, 8], "y_true": [3, -0.5, 2, 7]}], topics=["ML Metrics"]),
    mk("m_mape", "ML Metrics", "MAPE", 3, "mape",
       "Mean absolute percentage error.", "mean(|yt-yp|/|yt|)",
       "def mape(y_pred, y_true):\n    return float(np.mean(np.abs((y_true - y_pred) / y_true)))\n",
       [{"y_pred": [90, 110, 200], "y_true": [100, 100, 250]}], topics=["ML Metrics"]),
    mk("m_topk", "ML Metrics", "Top-K Accuracy", 4, "top_k_accuracy",
       "Fraction where true label is in the top-k logits.", "mean(label in top-k)",
       "def top_k_accuracy(logits, labels, k):\n    k = int(k)\n    labels = labels.astype(int)\n    correct = 0\n    for i in range(logits.shape[0]):\n        topk = np.argsort(logits[i])[-k:]\n        if labels[i] in topk:\n            correct += 1\n    return float(correct / logits.shape[0])\n",
       [{"logits": [[0.1, 0.2, 0.7], [0.6, 0.3, 0.1]], "labels": [2, 1], "k": 2}], topics=["ML Metrics"]),

    # ============================ ML FROM SCRATCH ============================
    mk("ml_linreg_predict", "ML Algorithms", "Linear Regression Predict", 2, "linreg_predict",
       "Predict y = Xw + b.", "Xw + b",
       "def linreg_predict(X, w, b):\n    return X @ w + b\n",
       [{"X": [[1, 2], [3, 4]], "w": [0.5, -1.0], "b": 1.0}], topics=["ML Algorithms"]),
    mk("ml_linreg_fit", "ML Algorithms", "Linear Regression (Normal Eq.)", 5, "linreg_fit",
       "Closed-form least squares weights.", "w = (XᵀX)⁻¹Xᵀy",
       "def linreg_fit(X, y):\n    return np.linalg.solve(X.T @ X, X.T @ y)\n",
       [{"X": [[1, 1], [1, 2], [1, 3]], "y": [1, 2, 3]}], topics=["ML Algorithms", "Linear Algebra"],
       mistakes=["Solve the normal equations rather than inverting XᵀX directly."]),
    mk("ml_logistic_proba", "ML Algorithms", "Logistic Regression Proba", 3, "logistic_proba",
       "Sigmoid of the linear score.", "σ(Xw + b)",
       "def logistic_proba(X, w, b):\n    z = X @ w + b\n    return 1.0 / (1.0 + np.exp(-z))\n",
       [{"X": [[1, 2], [-1, -2]], "w": [0.5, 0.5], "b": 0.0}], topics=["ML Algorithms"]),
    mk("ml_knn", "ML Algorithms", "k-NN Predict (from distances)", 4, "knn_predict",
       "Majority label among the k nearest.", "mode of k smallest distances",
       "def knn_predict(distances, labels, k):\n    k = int(k)\n    labels = labels.astype(int)\n    idx = np.argsort(distances)[:k]\n    vals = labels[idx]\n    return int(np.bincount(vals).argmax())\n",
       [{"distances": [0.2, 1.5, 0.3, 2.0], "labels": [1, 0, 1, 0], "k": 3}], topics=["ML Algorithms"]),
    mk("ml_kmeans_assign", "ML Algorithms", "k-Means Assignment", 4, "kmeans_assign",
       "Assign each point to its nearest centroid.", "argmin_c ||x - c||",
       "def kmeans_assign(points, centroids):\n    out = []\n    for p in points:\n        d = np.sum((centroids - p) ** 2, axis=1)\n        out.append(int(np.argmin(d)))\n    return out\n",
       [{"points": [[0, 0], [5, 5], [1, 0]], "centroids": [[0, 0], [5, 5]]}], topics=["ML Algorithms", "Clustering"]),
    mk("ml_onehot", "ML Algorithms", "One-Hot Encode", 2, "one_hot_encode",
       "Encode integer labels as one-hot rows.", "I[label]",
       "def one_hot_encode(labels, num_classes):\n    labels = labels.astype(int)\n    return np.eye(int(num_classes))[labels]\n",
       [{"labels": [0, 2, 1], "num_classes": 3}], topics=["ML Algorithms", "Feature Engineering"]),
    mk("ml_label_encode", "ML Algorithms", "Label Encode", 3, "label_encode",
       "Map string categories to ints by sorted order.", "rank of sorted unique",
       "def label_encode(items):\n    classes = sorted(set(items))\n    mapping = {c: i for i, c in enumerate(classes)}\n    return [mapping[x] for x in items]\n",
       [{"items": ["cat", "dog", "cat", "bird"]}], topics=["ML Algorithms", "Feature Engineering"]),
    mk("ml_gini", "ML Algorithms", "Gini Impurity", 3, "gini_impurity",
       "Impurity of a label distribution.", "1 - sum(p^2)",
       "def gini_impurity(p):\n    return float(1 - np.sum(p ** 2))\n",
       [{"p": [0.5, 0.5]}, {"p": [1.0, 0.0]}], topics=["ML Algorithms", "Trees"]),
    mk("ml_minmax_scaler", "ML Algorithms", "Min-Max Scaler (per column)", 3, "minmax_scaler",
       "Scale each feature column to [0,1].", "(x-min)/(max-min) per col",
       "def minmax_scaler(X):\n    lo = X.min(axis=0)\n    hi = X.max(axis=0)\n    return (X - lo) / (hi - lo)\n",
       [{"X": [[1, 10], [2, 20], [3, 30]]}], topics=["ML Algorithms", "Feature Engineering"]),

    # ============================ DATA MANIPULATION ============================
    mk("dm_value_counts", "Data Manipulation", "Value Counts", 2, "value_counts",
       "Count occurrences of each category.", "{value: count}",
       "def value_counts(items):\n    counts = {}\n    for it in items:\n        counts[it] = counts.get(it, 0) + 1\n    return counts\n",
       [{"items": ["a", "b", "a", "c", "a"]}], topics=["Data Manipulation"]),
    mk("dm_groupby_mean", "Data Manipulation", "Group-By Mean", 4, "groupby_mean",
       "Average values within each group key.", "mean(value | key)",
       "def groupby_mean(keys, values):\n    groups = {}\n    for k, v in zip(keys, values):\n        groups.setdefault(k, []).append(v)\n    return {k: float(sum(vs) / len(vs)) for k, vs in groups.items()}\n",
       [{"keys": ["a", "b", "a", "b"], "values": [1, 2, 3, 4]}], topics=["Data Manipulation"]),
    mk("dm_filter_gt", "Data Manipulation", "Filter Greater Than", 1, "filter_greater_than",
       "Keep elements greater than a threshold.", "x[x > t]",
       "def filter_greater_than(x, t):\n    return x[x > t]\n",
       [{"x": [1, 5, 2, 8, 3], "t": 3}], topics=["Data Manipulation"]),
    mk("dm_sort_desc", "Data Manipulation", "Sort Descending", 1, "sort_descending",
       "Sort values high to low.", "sort desc",
       "def sort_descending(x):\n    return np.sort(x)[::-1]\n",
       [{"x": [3, 1, 4, 1, 5]}], topics=["Data Manipulation"]),
    mk("dm_unique_sorted", "Data Manipulation", "Unique Sorted", 1, "unique_sorted",
       "Distinct values, ascending.", "sorted set",
       "def unique_sorted(x):\n    return np.unique(x)\n",
       [{"x": [3, 1, 2, 3, 1]}], topics=["Data Manipulation"]),
    mk("dm_dedup_order", "Data Manipulation", "Drop Duplicates (keep order)", 3, "drop_duplicates",
       "Remove repeats, preserve first-seen order.", "stable unique",
       "def drop_duplicates(items):\n    seen = set()\n    out = []\n    for it in items:\n        if it not in seen:\n            seen.add(it)\n            out.append(it)\n    return out\n",
       [{"items": ["a", "b", "a", "c", "b"]}], topics=["Data Manipulation"]),
    mk("dm_fillna_mean", "Data Manipulation", "Fill NaN with Mean", 3, "fillna_mean",
       "Replace missing (NaN) with the column mean.", "x[nan] = mean(x)",
       "def fillna_mean(x):\n    m = np.nanmean(x)\n    return np.where(np.isnan(x), m, x)\n",
       [{"x": [1.0, None, 3.0, None, 5.0]}], topics=["Data Manipulation"],
       mistakes=["Compute the mean ignoring NaNs (np.nanmean)."]),
    mk("dm_running_max", "Data Manipulation", "Running Maximum", 2, "running_max",
       "Cumulative max along the array.", "cummax",
       "def running_max(x):\n    return np.maximum.accumulate(x)\n",
       [{"x": [1, 3, 2, 5, 4]}], topics=["Data Manipulation", "Time Series"]),
    mk("dm_rank", "Data Manipulation", "Rank Data", 3, "rank_data",
       "Ordinal rank (1-based) of each element.", "rank by value",
       "def rank_data(x):\n    order = np.argsort(x)\n    ranks = np.empty(len(x), dtype=int)\n    ranks[order] = np.arange(1, len(x) + 1)\n    return ranks\n",
       [{"x": [30, 10, 20]}], topics=["Data Manipulation"]),

    # ============================ TIME SERIES ============================
    mk("ts_moving_avg", "Time Series", "Moving Average", 3, "moving_average",
       "Simple moving average of window w.", "mean of each window",
       "def moving_average(x, w):\n    w = int(w)\n    return np.convolve(x, np.ones(w) / w, mode='valid')\n",
       [{"x": [1, 2, 3, 4, 5], "w": 3}], topics=["Time Series"]),
    mk("ts_diff", "Time Series", "First Difference", 1, "diff_series",
       "Consecutive differences.", "x_t - x_{t-1}",
       "def diff_series(x):\n    return np.diff(x)\n",
       [{"x": [1, 3, 6, 10]}], topics=["Time Series"]),
    mk("ts_ema", "Time Series", "Exponential Smoothing", 4, "exp_smoothing",
       "EWMA with factor alpha.", "s_t = αx_t + (1-α)s_{t-1}",
       "def exp_smoothing(x, alpha):\n    s = [x[0]]\n    for t in range(1, len(x)):\n        s.append(alpha * x[t] + (1 - alpha) * s[-1])\n    return np.array(s)\n",
       [{"x": [3, 5, 8, 6], "alpha": 0.5}], topics=["Time Series"]),

    # ============================ DISTANCES / SIMILARITY ============================
    mk("ds_hamming", "Distances", "Hamming Distance", 2, "hamming_distance",
       "Count of differing positions.", "sum(a != b)",
       "def hamming_distance(a, b):\n    return int(np.sum(np.array(a) != np.array(b)))\n",
       [{"a": [1, 0, 1, 1], "b": [1, 1, 1, 0]}], topics=["Distances"]),
    mk("ds_jaccard", "Distances", "Jaccard Similarity", 3, "jaccard_similarity",
       "|A∩B| / |A∪B| for two sets.", "intersection/union",
       "def jaccard_similarity(a, b):\n    sa, sb = set(a), set(b)\n    return float(len(sa & sb) / len(sa | sb))\n",
       [{"a": ["x", "y", "z"], "b": ["y", "z", "w"]}], topics=["Distances", "NLP"]),
    mk("ds_minkowski", "Distances", "Minkowski Distance", 3, "minkowski_distance",
       "Generalized Lp distance.", "(sum|a-b|^p)^{1/p}",
       "def minkowski_distance(a, b, p):\n    return float(np.sum(np.abs(a - b) ** p) ** (1.0 / p))\n",
       [{"a": [0, 0], "b": [3, 4], "p": 2}], topics=["Distances"]),

    # ============================ FEATURE ENGINEERING ============================
    mk("fe_poly2", "Feature Engineering", "Polynomial Features (deg 2)", 3, "poly_features_2",
       "Expand x to [1, x, x²] per sample.", "[1, x, x^2]",
       "def poly_features_2(x):\n    return np.stack([np.ones_like(x), x, x ** 2], axis=1)\n",
       [{"x": [1, 2, 3]}], topics=["Feature Engineering"]),
    mk("fe_log", "Feature Engineering", "Log Transform", 1, "log_transform",
       "Natural log of (1 + x).", "log1p(x)",
       "def log_transform(x):\n    return np.log1p(x)\n",
       [{"x": [0, 1, 9]}], topics=["Feature Engineering"]),
    mk("fe_binarize", "Feature Engineering", "Binarize at Threshold", 1, "binarize",
       "1 if x > t else 0.", "[x > t]",
       "def binarize(x, t):\n    return (x > t).astype(int)\n",
       [{"x": [0.2, 0.8, 0.5, 0.9], "t": 0.5}], topics=["Feature Engineering"]),
    mk("fe_hist", "Feature Engineering", "Histogram Bin Counts", 3, "bin_counts",
       "Count values per equal-width bin.", "histogram",
       "def bin_counts(x, bins):\n    counts, _ = np.histogram(x, bins=int(bins))\n    return counts\n",
       [{"x": [0.1, 0.4, 0.5, 0.9, 0.95], "bins": 2}], topics=["Feature Engineering", "Statistics"]),

    # ============================ NLP BASICS ============================
    mk("nlp_tokencount", "NLP", "Word Count", 2, "word_count",
       "Count words in a sentence.", "{word: count}",
       "def word_count(sentence):\n    counts = {}\n    for w in sentence.lower().split():\n        counts[w] = counts.get(w, 0) + 1\n    return counts\n",
       [{"sentence": "the cat the dog the"}], topics=["NLP", "Data Manipulation"]),
    mk("nlp_bow", "NLP", "Bag of Words", 4, "bag_of_words",
       "Count vocab words in a document.", "counts over vocab",
       "def bag_of_words(doc, vocab):\n    words = doc.lower().split()\n    return [int(words.count(v)) for v in vocab]\n",
       [{"doc": "cat dog cat", "vocab": ["cat", "dog", "bird"]}], topics=["NLP"]),
    mk("nlp_tf", "NLP", "Term Frequency", 3, "term_frequency",
       "Word counts normalized by length.", "count/total",
       "def term_frequency(doc, vocab):\n    words = doc.lower().split()\n    n = len(words)\n    return [words.count(v) / n for v in vocab]\n",
       [{"doc": "a a b", "vocab": ["a", "b"]}], topics=["NLP"]),
    mk("nlp_ngrams", "NLP", "Character Bigrams", 3, "bigrams",
       "Adjacent token pairs joined by space.", "pairs (t_i, t_{i+1})",
       "def bigrams(tokens):\n    return [tokens[i] + ' ' + tokens[i+1] for i in range(len(tokens) - 1)]\n",
       [{"tokens": ["i", "love", "data"]}], topics=["NLP"]),

    # ============================ CLASSIC ALGORITHMS (DS-flavored) ============================
    mk("alg_two_sum", "Algorithms", "Two Sum (indices)", 2, "two_sum",
       "Indices of the two numbers summing to target.", "i,j : a_i+a_j=target",
       "def two_sum(nums, target):\n    seen = {}\n    for i, v in enumerate(nums):\n        need = target - v\n        if need in seen:\n            return [seen[need], i]\n        seen[v] = i\n    return []\n",
       [{"nums": [2, 7, 11, 15], "target": 9}, {"nums": [3, 2, 4], "target": 6}], topics=["Algorithms"]),
    mk("alg_binsearch", "Algorithms", "Binary Search", 2, "binary_search",
       "Index of target in a sorted array, or -1.", "O(log n) search",
       "def binary_search(arr, target):\n    lo, hi = 0, len(arr) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if arr[mid] == target:\n            return mid\n        elif arr[mid] < target:\n            lo = mid + 1\n        else:\n            hi = mid - 1\n    return -1\n",
       [{"arr": [1, 3, 5, 7, 9], "target": 7}, {"arr": [1, 2, 3], "target": 4}], topics=["Algorithms"]),
    mk("alg_fib", "Algorithms", "Fibonacci (iterative)", 1, "fibonacci",
       "n-th Fibonacci number (0-indexed).", "F_n",
       "def fibonacci(n):\n    n = int(n)\n    a, b = 0, 1\n    for _ in range(n):\n        a, b = b, a + b\n    return a\n",
       [{"n": 10}, {"n": 0}], topics=["Algorithms"]),
    mk("alg_sliding_max", "Algorithms", "Max Subarray Sum (Kadane)", 4, "max_subarray_sum",
       "Largest contiguous subarray sum.", "Kadane's algorithm",
       "def max_subarray_sum(nums):\n    best = cur = nums[0]\n    for v in nums[1:]:\n        cur = max(v, cur + v)\n        best = max(best, cur)\n    return float(best)\n",
       [{"nums": [-2, 1, -3, 4, -1, 2, 1, -5, 4]}], topics=["Algorithms"]),
]
