"""Add visibility to papers

Revision ID: a1ad010652f1
Revises: i1j2k3l4m5n6
Create Date: 2026-06-28 23:49:25.559968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ad010652f1'
down_revision: Union[str, Sequence[str], None] = 'i1j2k3l4m5n6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paper_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_modules_paper_id'), ['paper_id'], unique=False)

    with op.batch_alter_table('paper_part_submissions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pps_user_part'))

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visibility', sa.String(length=20), server_default='public', nullable=False))
        batch_op.add_column(sa.Column('terms_accepted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('uploaded_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('r2_key', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('is_flagged', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('flag_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('file_size_bytes', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_papers_uploaded_by'), ['uploaded_by'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['uploaded_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hashed_password', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('weekly_points', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('storage_bytes_used', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('is_email_verified', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('is_verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('token_version', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('totp_secret', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('mfa_enabled', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('backup_codes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('lockout_until', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('email_drip_opt_out', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('email_digest', sa.Boolean(), server_default='false', nullable=False))
        batch_op.create_index('ix_user_points_desc', ['points'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_user_points_desc')
        batch_op.drop_column('email_digest')
        batch_op.drop_column('email_drip_opt_out')
        batch_op.drop_column('lockout_until')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('backup_codes')
        batch_op.drop_column('mfa_enabled')
        batch_op.drop_column('totp_secret')
        batch_op.drop_column('token_version')
        batch_op.drop_column('is_verified')
        batch_op.drop_column('email_verified_at')
        batch_op.drop_column('is_email_verified')
        batch_op.drop_column('is_admin')
        batch_op.drop_column('storage_bytes_used')
        batch_op.drop_column('weekly_points')
        batch_op.drop_column('hashed_password')

    with op.batch_alter_table('papers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_papers_uploaded_by'))
        batch_op.drop_column('file_size_bytes')
        batch_op.drop_column('flag_reason')
        batch_op.drop_column('is_flagged')
        batch_op.drop_column('r2_key')
        batch_op.drop_column('uploaded_by')
        batch_op.drop_column('terms_accepted_at')
        batch_op.drop_column('visibility')

    with op.batch_alter_table('paper_part_submissions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pps_user_part'), ['user_id', 'part_id'], unique=False)

    with op.batch_alter_table('paper_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_modules_paper_id'))

    # ### end Alembic commands ###
