"""Add Paper and PaperModule

Revision ID: b073274a0070
Revises: 5ca65965e66d
Create Date: 2026-05-30 19:00:20.104386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b073274a0070'
down_revision: Union[str, Sequence[str], None] = '5ca65965e66d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('papers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('authors', sa.String(length=1024), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('architecture_graph', sa.JSON(), nullable=True),
    sa.Column('flops_analysis', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_papers_id'), 'papers', ['id'], unique=False)
    op.create_table('paper_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paper_id', sa.Integer(), nullable=False),
    sa.Column('layer_name', sa.String(length=255), nullable=False),
    sa.Column('module_type', sa.String(length=128), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('tensor_flow', sa.JSON(), nullable=True),
    sa.Column('graph_nodes', sa.JSON(), nullable=True),
    sa.Column('flops_context', sa.JSON(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_modules_id'), 'paper_modules', ['id'], unique=False)
    op.drop_index(op.f('ix_problems_id'), table_name='problems')
    op.drop_table('problems')
    op.drop_index(op.f('ix_submissions_id'), table_name='submissions')
    op.drop_table('submissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submissions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('problem_id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.TEXT(), nullable=False),
    sa.Column('passed', sa.BOOLEAN(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=32), nullable=True),
    sa.Column('runtime_logs', sa.TEXT(), nullable=True),
    sa.Column('points_awarded', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_id'), 'submissions', ['id'], unique=False)
    op.create_table('problems',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=512), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=128), nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=6), nullable=False),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('starter_code', sa.TEXT(), nullable=False),
    sa.Column('test_cases', sqlite.JSON(), nullable=False),
    sa.Column('points_reward', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_problems_id'), 'problems', ['id'], unique=False)
    op.drop_index(op.f('ix_paper_modules_id'), table_name='paper_modules')
    op.drop_table('paper_modules')
    op.drop_index(op.f('ix_papers_id'), table_name='papers')
    op.drop_table('papers')
    # ### end Alembic commands ###
