"""add_fk_indexes

Revision ID: cc3efb9d9907
Revises: b073274a0070
Create Date: 2026-06-25 02:09:16.628515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc3efb9d9907'
down_revision: Union[str, Sequence[str], None] = 'b073274a0070'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learner_progress', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_progress', ['learner_id', 'entity_type', 'entity_id'])

    with op.batch_alter_table('paper_modules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_modules_paper_id'), ['paper_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_user_id'))

    with op.batch_alter_table('paper_modules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_modules_paper_id'))

    with op.batch_alter_table('learner_progress', schema=None) as batch_op:
        batch_op.drop_constraint('uq_progress', type_='unique')

    # ### end Alembic commands ###
